steps:
  name: Run Python Tests
  on:
    push:
      branches:
        - development

  jobs:
    build:
      strategy:
        matrix:
          platform: [ubuntu-latest, macos-latest, windows-latest]
      runs-on: ${{matrix.platform}}
      steps:
        - uses: actions/checkout@v2
        - name: Install Python 3
          uses: actions/setup-python@v1
          with:
            python-version: 3.8
        - name: Install dependencies
          run: |
            python3 -m pip install --upgrade pip
            pip3 install -r requirements.txt
        - name: Run tests with pytest
          run: python3 -m unittest discover unit_test/

  name: Codecov
  # You may pin to the exact commit or the version.
  # uses: codecov/codecov-action@f32b3a3741e1053eb607407145bc9619351dc93b
  uses: codecov/codecov-action@v2.1.0
  with:
    fail_ci_if_error: true